/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_inscription_SEW (void);
GtkWidget* create_window_authenti_SEW (void);
GtkWidget* create_window_Etudiant_SEW (void);
GtkWidget* create_principale_FBA (void);
GtkWidget* create_Ajouter_FBA (void);
GtkWidget* create_modifier_FBA (void);
GtkWidget* create_Supprimer_FBA (void);
GtkWidget* create_calcul_FBA (void);
GtkWidget* create_window_connexion_hedi (void);
GtkWidget* create_window_menu_hedi (void);
GtkWidget* create_window_ajouter_hedi (void);
GtkWidget* create_window_modifier_hedi (void);
GtkWidget* create_window_supprimer_hedi (void);
GtkWidget* create_window_afficher_hedi (void);
GtkWidget* create_fenetre_ajout_Aziz (void);
GtkWidget* create_fenetre_recherche_Aziz (void);
GtkWidget* create_fenetre_rupture_Aziz (void);
GtkWidget* create_fenetre_suppr_Aziz (void);
GtkWidget* create_fenetre_main_Aziz (void);
GtkWidget* create_dashboard (void);
GtkWidget* create_mod (void);
GtkWidget* create_af (void);
GtkWidget* create_aj (void);
GtkWidget* create_windowGestionCapteurs (void);
GtkWidget* create_windowListeCapteurs (void);
GtkWidget* create_windowAjoutSucc (void);
GtkWidget* create_windowModifSucc (void);
GtkWidget* create_windowSupSucc (void);
GtkWidget* create_windowRemplir (void);
GtkWidget* create_window1 (void);
GtkWidget* create_windowID (void);
GtkWidget* create_windowModifierCapteur (void);
GtkWidget* create_ModifierCapteur (void);
GtkWidget* create_windowAjoutCapteur (void);
GtkWidget* create_window_menu_etudiant (void);
GtkWidget* create_window2 (void);
GtkWidget* create_window3 (void);
GtkWidget* create_window4 (void);
